name: CI

on:
  push:
    branches: [ main, envoyou/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      full_regression:
        description: "Run full regression (ENVOYOU_RUN_ALL_TESTS=true)"
        required: false
        default: "false"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ENVOYOU_RUN_ALL_TESTS: ${{ github.event.inputs.full_regression || 'false' }}
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (Envoyou-focused by default)
        run: |
          pytest -q
